# Generated by Django 4.2.7 on 2023-12-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='datosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=150)),
                ('correo', models.CharField(max_length=150)),
                ('celular', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('fechaNacimiento', models.DateField()),
            ],
        ),
    ]
