# Generated by Django 4.2.7 on 2023-12-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_alter_datospersonales_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='biografia',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
