# Generated by Django 4.2.7 on 2023-12-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_datospersonales_biografia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('link', models.TextField()),
                ('imagen', models.CharField(max_length=50)),
            ],
        ),
    ]
