# Generated by Django 4.2.7 on 2023-12-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_estudios_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='descripcion',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
