# Generated by Django 4.2.7 on 2023-12-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0007_experiencialaboral_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='linkedin',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
